### ISSUE TITLE
Update example text for series processing to take tokens into consideration

### ISSUE THREAD

**Issue by ct-clearhaus** [clearhaus/gateway-api-docs#190]
The section https://docs.gateway.clearhaus.com/#repeatedly-reserve-money lacks an update since the introduction of tokens; it seems we missed it as part of https://github.com/clearhaus/gateway-api-docs/pull/149 (or the subsequent adjustments).

It should be clarified that tokens can also be used for series processing both for first-in-series and subsequent-in-series authorizations.

**Comment by ct-clearhaus** [comment]
This finding is courtesy of @nikiepaydk. ❤️

**Comment by mt-clearhaus** [comment]
I have created https://github.com/clearhaus/gateway-api-docs/pull/191.

**Comment by cbobach** [comment]
@mt-clearhaus the PR looks fine from my point of view. Don't know if we want anybody else to take a look too, else please just reach out.

**Comment by mt-clearhaus** [comment]
https://github.com/clearhaus/gateway-api-docs/pull/191 has been merged :heavy_check_mark:
